### ISSUE TITLE
Example of sending an entire file

### ISSUE THREAD

**Issue by GP4cK** [philippfranke/multipart-related#1]
Hello!
I' trying to send a file to a SOAP service that seem to only accept content-type of multipart/related and I am wondering what is the best way to do it...

Should I make a loop, read a few bytes and use `w.CreatePart()` at every iteration? Kind of like in the README.md? This doesn't seem very efficient. Isn't there a way to use `io.Copy()`?

Thanks for your help!

**Comment by philippfranke** [comment]
Hey Gujie,

As mentioned in the README.md a multipart/related contains multiple components/files which are related to each other. Usually, each part represents a file. For example, you’re going to upload an images with metadata(like tags, categories, etc) formatted in json. The image would be part 1 and the metadata would be part 2. 

Thus, you need to iterate over your content(image, metadata) and copy each into a part. Unfortunately, this package doesn’t support media type sniffing so you need to set your content-type explicitly.

``` go
image_header := textproto.MIMEHeader{}
image_header.Add("Content-Type", "images/jpeg")
image_part, _ := w.CreatePart("", image_header)
io.Copy(image_part, image_file)

json_header := textproto.MIMEHeader{}
json_header.Add("Content-Type", "application/json")
json_part, _ := w.CreatePart("", json_header )
io.Copy(json_part , json_output)
```

**Comment by GP4cK** [comment]
Thanks, it's working now!
